version: '3.1'
services:
  mysql:
    image: mariadb:10.7
    container_name: booking-mysql
    command: mysqld --sql_mode="NO_ENGINE_SUBSTITUTION"
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=booking
      - MYSQL_USER=user
      - MYSQL_PASSWORD=user
    ports:
      - '3306:3306'
  redis:
    image: redis:alpine
    container_name: booking-redis
    ports:
      - '6379:6379'
  localstack:
    image: localstack/localstack:0.13.3
    container_name: booking-localstack
    environment:
      - SERVICES=s3,
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
      - AWS_ACCESS_KEY_ID=123
      - AWS_SECRET_ACCESS_KEY=xyz
    ports:
      - '4563-4599:4563-4599'
      - '8055:8080'
    volumes:
      - './volumes/s3-storage/.init:/docker-entrypoint-initaws.d'
      - './volumes/s3-storage/.localstack:/tmp/localstack'
volumes:
  mysql-data:
