version: '3.1'
services:
  mysql:
    image: mysql:5.7
    container_name: booking-mysql
    command: mysqld --sql_mode="NO_ENGINE_SUBSTITUTION"
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=booking
      - MYSQL_USER=user
      - MYSQL_PASSWORD=user
    ports:
      - '3306:3306'
  redis:
    image: redis:alpine
    container_name: booking-redis
    ports:
      - '6379:6379'
volumes:
  mysql-data:
