services:
  Infrastructure.Web.Healthcheck.HealthCheckController:
    class: ../../../Infrastructure/Web/Healthcheck/HealthcheckController
    arguments: []

  Infrastructure.Web.Partner.PartnerGetController:
    class: ../../../Infrastructure/Web/Partner/PartnerGetController
    arguments: []

  Infrastructure.Web.Partner.PartnerPostController:
    class: ../../../Infrastructure/Web/Partner/PartnerPostController
    arguments: []

  Infrastructure.Web.Partner.PartnerGetBySubdomainController:
    class: ../../../Infrastructure/Web/Partner/PartnerGetBySubdomainController
    arguments: []

  Infrastructure.Web.Partner.PartnerGetByEmailController:
    class: ../../../Infrastructure/Web/Partner/PartnerGetByEmailController
    arguments: []

  Infrastructure.Web.Activity.ActivityPostController:
    class: ../../../Infrastructure/Web/Activity/ActivityPostController
    arguments: []

  Infrastructure.Web.Activity.ActivityPutController:
    class: ../../../Infrastructure/Web/Activity/ActivityPutController
    arguments: []

  Infrastructure.Web.Activity.ActivityGetByPartnerController:
    class: ../../../Infrastructure/Web/Activity/ActivityGetByPartnerController
    arguments: []

  Infrastructure.Web.Activity.ActivityGetController:
    class: ../../../Infrastructure/Web/Activity/ActivityGetController
    arguments: []

  Infrastructure.Web.Activity.ActivityPostImageController:
    class: ../../../Infrastructure/Web/Activity/ActivityPostImageController
    arguments: []

  Infrastructure.Web.Activity.ActivityDeleteController:
    class: ../../../Infrastructure/Web/Activity/ActivityDeleteController
    arguments: []

  Infrastructure.Web.Event.EventPostController:
    class: ../../../Infrastructure/Web/Event/EventPostController
    arguments: []

  Infrastructure.Web.Event.EventPutController:
    class: ../../../Infrastructure/Web/Event/EventPutController
    arguments: []

  Infrastructure.Web.Event.EventGetByActivityController:
    class: ../../../Infrastructure/Web/Event/EventGetByActivityController
    arguments: []

  Infrastructure.Web.Event.EventGetController:
    class: ../../../Infrastructure/Web/Event/EventGetController
    arguments: []

  Infrastructure.Web.Event.EventDeleteController:
    class: ../../../Infrastructure/Web/Event/EventDeleteController
    arguments: []

  Infrastructure.Web.Booking.BookingGetByEventController:
    class: ../../../Infrastructure/Web/Booking/BookingGetByEventController
    arguments: []

  Infrastructure.Web.Booking.BookingInitPostController:
    class: ../../../Infrastructure/Web/Booking/BookingInitPostController
    arguments: []

  Infrastructure.Web.Booking.BookingGuestPostController:
    class: ../../../Infrastructure/Web/Booking/BookingGuestPostController
    arguments: []

  Infrastructure.Web.Booking.BookingFinishPostController:
    class: ../../../Infrastructure/Web/Booking/BookingFinishPostController
    arguments: []

  Infrastructure.Web.Booking.BookingGetController:
    class: ../../../Infrastructure/Web/Booking/BookingGetController
    arguments: []

  Infrastructure.Web.Booking.BookingPutController:
    class: ../../../Infrastructure/Web/Booking/BookingPutController
    arguments: []

  Infrastructure.Web.Booking.BookingListByEventController:
    class: ../../../Infrastructure/Web/Booking/BookingListByEventController
    arguments: []

  Infrastructure.Web.Booking.BookingListWithFiltersController:
    class: ../../../Infrastructure/Web/Booking/BookingListWithFiltersController
    arguments: []

  Infrastructure.Web.Guest.GuestPostController:
    class: ../../../Infrastructure/Web/Guest/GuestPostController
    arguments: []

  Infrastructure.Web.Guest.GuestPutController:
    class: ../../../Infrastructure/Web/Guest/GuestPutController
    arguments: []

  Infrastructure.Web.Guest.GuestGetController:
    class: ../../../Infrastructure/Web/Guest/GuestGetController
    arguments: []

  Infrastructure.Web.Guest.GuestsGetController:
    class: ../../../Infrastructure/Web/Guest/GuestsGetController
    arguments: []

  Infrastructure.Web.Guest.GuestDeleteController:
    class: ../../../Infrastructure/Web/Guest/GuestDeleteController
    arguments: []

  Infrastructure.Web.Pass.PassPostController:
    class: ../../../Infrastructure/Web/Pass/PassPostController
    arguments: []

  Infrastructure.Web.Pass.PassPutController:
    class: ../../../Infrastructure/Web/Pass/PassPutController
    arguments: []

  Infrastructure.Web.Pass.PassDeleteController:
    class: ../../../Infrastructure/Web/Pass/PassDeleteController
    arguments: []

  Infrastructure.Web.Pass.PassGetController:
    class: ../../../Infrastructure/Web/Pass/PassGetController
    arguments: []

  Infrastructure.Web.Pass.PassGetByPartnerController:
    class: ../../../Infrastructure/Web/Pass/PassGetByPartnerController
    arguments: []

  Infrastructure.Web.GuestPass.GuestPassPostController:
    class: ../../../Infrastructure/Web/GuestPass/GuestPassPostController
    arguments: []

  Infrastructure.Web.GuestPass.GuestPassPutController:
    class: ../../../Infrastructure/Web/GuestPass/GuestPassPutController
    arguments: []

  Infrastructure.Web.GuestPass.GuestPassGetByGuestController:
    class: ../../../Infrastructure/Web/GuestPass/GuestPassGetByGuestController
    arguments: []

  Infrastructure.Web.GuestPass.GuestPassGetController:
    class: ../../../Infrastructure/Web/GuestPass/GuestPassGetController
    arguments: []

  Infrastructure.Web.GuestPass.GuestPassDeleteController:
    class: ../../../Infrastructure/Web/GuestPass/GuestPassDeleteController
    arguments: []
