services:
  Application.Booking.UpdateBooking:
    class: ../../Application/Booking/UpdateBooking
    arguments:
      [
        '@Infrastructure.Repository.BookingMysqlRepository',
        '@Application.Event.UpdateCurrentCapacityEvent',
        '@Application.GuestPass.UpdateCurrentCapacityGuestPass'
      ]
  Application.Event.UpdateCurrentCapacityEvent:
    class: ../../Application/Event/UpdateCurrentCapacityEvent
    arguments: ['@Infrastructure.Repository.EventMysqlRepository']

  Application.GuestPass.UpdateCurrentCapacityGuestPass:
    class: ../../Application/GuestPass/UpdateCurrentCapacityGuestPass
    arguments: ['@Infrastructure.Repository.GuestPassRepository']

  Application.Calendar.CreateCalendarEvent:
    class: ../../Application/Calendar/CreateCalendarEvent
    arguments: []

  Application.Calendar.DeleteCalendarEvent:
    class: ../../Application/Calendar/DeleteCalendarEvent
    arguments: []

